-- COMANDOS PARA CRIAR BANCO DE DADOS
CREATE DATABASE CLINICA_MEDICA_MONYKE;
CREATE DATABASE CLINICA_MEDICA_MONYKE2;

-- COMANDO PARA APAGAR BANCO DE DADOS
DROP DATABASE CLINICA_MEDICA_MONYKE2;

-- COMANDO PARA ATIVAR BANCO DE DADOS
USE CLINICA_MEDICA_MONYKE;

-- MOSTRAR TABELAS NO BANCO DE DADOS
SHOW TABLES;

-- COMANDO PARA CRIAR TABELAS
CREATE TABLE MEDICO (
Id_Medico int auto_increment primary key,
Nome varchar(60) not null,
Horario_do_plantao time not null,
Salario decimal(5,2)
);

CREATE TABLE CONSULTA (
Id_Consulta int auto_increment primary key,
Horario time not null,
Data datetime not null,
Nome_Medico varchar(60) not null
);

CREATE TABLE PACIENTES (
Id_Pacientes int auto_increment primary key,
CPF varchar(60) not null,
Nome_Completo varchar(60) not null
);

-- COMANDOS PARA ALTERAR INFORMAÇÕES
-- ADICIONAR UM NOVO ATRIBUTO
ALTER TABLE PACIENTES ADD TELEFONE VARCHAR(15);

-- ALTERAR O TIPO DE DADOS E TAMANHO DO ATRIBUTO
ALTER TABLE PACIENTES MODIFY TELEFONE VARCHAR(15);

-- RENOMEAR O NOME DO ATRIBUTO
-- ALTER TABLE ALUNOS CHANGE TELEFONE CELULAR(15);

-- EXCLUIR ATIBUTO
ALTER TABLE PACIENTES DROP COLUMN TELEFONE;

-- RENOMEAR TABELAS
ALTER TABLE CONSULTA RENAME TO CONSULTAS;

-- EXCLUIR ATRIBUTO
ALTER TABLE PACIENTES DROP COLUMN TELEFONE;
